version: 2
updates:
  - package-ecosystem: 'npm'
    directory: '/'
    schedule:
      interval: 'daily'
    assignees:
      - 'kdev'
    commit-message:
        prefix: 'chore'
        include: 'scope'
    reviewers:
      - 'kdev'
    open-pull-requests-limit: 10

  - package-ecosystem: 'github-actions'
    directory: '/'
    schedule:
       interval: 'daily'
    assignees:
      - 'kdev'
    commit-message:
      prefix: 'chore'
      include: 'scope'
    reviewers:
      - 'kdev'
